#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Idempotent Azure SQL data-access configuration: creates the contained database user for the
    App Service's data-access user-assigned managed identity and (optionally) applies EF Core migrations.

.DESCRIPTION
    Runs as a discrete CI step (not a Terraform provisioner), mirroring
    terraform/scripts/configure-external-id-sign-up.sh:
      1. The azurerm/azuread Terraform providers never open a SQL connection - "CREATE USER ..."
         is T-SQL, not an ARM/Graph operation, so it cannot be a Terraform resource.
      2. The shared terraform-plan-and-apply composite authenticates only the Terraform providers
         via ARM_* OIDC env vars; it never leaves behind a usable SQL/Graph token. This script
         therefore runs after its own `azure/login`, using the same federated workload identity
         (no secrets - see standards.oidc-and-secrets) - which is also the SQL server's Entra admin
         (see terraform/sql.tf), so it is authorized to both create the contained user AND apply
         migrations.

    Two operations, both idempotent/re-runnable:
      A. Ensure a contained database user exists for -ManagedIdentityName (the App Service's dedicated
         data-access user-assigned identity), created by SID from -ManagedIdentityClientId and granted
         EXACTLY db_datareader + db_datawriter. The runtime managed identity never gets db_ddladmin or
         any schema-changing permission - migrations are applied here, by the admin, not by the app.
         Creating the user by SID (WITH SID = <client_id-bytes>, TYPE = E) avoids `FROM EXTERNAL
         PROVIDER`, which would require the SQL server identity to hold the Entra "Directory Readers"
         role (not granted to this workload).
      B. Apply the idempotent EF Core migrations script (see
         `dotnet ef migrations script --idempotent`, generated by the caller and passed via
         -MigrationsScriptPath) so the schema is current before the new App Service package can
         possibly start serving traffic.

.PARAMETER SqlServerFqdn
    Fully-qualified domain name of the Azure SQL logical server (terraform output
    sql_server_fully_qualified_domain_name).

.PARAMETER SqlDatabaseName
    Database name (terraform output sql_database_name).

.PARAMETER ManagedIdentityName
    Name of the user-assigned managed identity to grant data access to (terraform output
    sql_data_identity_name). Used verbatim as the contained database user name.

.PARAMETER ManagedIdentityClientId
    Client (application) ID of that managed identity (terraform output sql_data_identity_client_id).
    Converted to a binary SID so the contained user is created by SID
    (`CREATE USER [name] WITH SID = <sid>, TYPE = E`) rather than `FROM EXTERNAL PROVIDER` - the latter
    needs the SQL server's identity to hold the Entra "Directory Readers" role, which this workload
    neither has nor can self-grant. The SID form performs no directory lookup.

.PARAMETER MigrationsScriptPath
    Optional path to an idempotent EF Core migrations SQL script
    (`dotnet ef migrations script --idempotent`). When omitted, only the contained-user step runs.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $SqlServerFqdn,

    [Parameter(Mandatory = $true)]
    [string] $SqlDatabaseName,

    [Parameter(Mandatory = $true)]
    [string] $ManagedIdentityName,

    [Parameter(Mandatory = $true)]
    [string] $ManagedIdentityClientId,

    [Parameter(Mandatory = $false)]
    [string] $MigrationsScriptPath
)

$ErrorActionPreference = 'Stop'

# Azure SQL serverless (GP_S_*) auto-pauses after inactivity; the first connection triggers a resume
# that can take up to ~60s, during which the connection blocks in the post-login phase and a normal
# ~15-30s connection timeout expires ("Connection Timeout Expired ... post-login phase"). Wrap each
# Invoke-Sqlcmd in a retry with a generous per-attempt connection timeout so the deploy rides out the
# resume instead of failing on a cold database.
function Invoke-SqlWithResumeRetry {
    param(
        [Parameter(Mandatory = $true)][scriptblock] $Action,
        [int] $MaxAttempts = 6,
        [int] $DelaySeconds = 20
    )
    for ($attempt = 1; $attempt -le $MaxAttempts; $attempt++) {
        try {
            & $Action
            return
        }
        catch {
            if ($attempt -ge $MaxAttempts) { throw }
            $firstLine = ($_.Exception.Message -split "`n")[0]
            Write-Host "Attempt $attempt of $MaxAttempts failed ($firstLine). The serverless database may be resuming - retrying in $DelaySeconds s..."
            Start-Sleep -Seconds $DelaySeconds
        }
    }
}

if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
    throw "The Azure CLI ('az') is required and must already be logged in (see azure/login in the workflow)."
}

$sqlServerModule = Get-Module -ListAvailable -Name SqlServer | Select-Object -First 1
if (-not $sqlServerModule) {
    Write-Host "Installing the SqlServer PowerShell module (Invoke-Sqlcmd -AccessToken support)..."
    Install-Module -Name SqlServer -Scope CurrentUser -Force -AllowClobber -MinimumVersion 22.2.0
}
Import-Module SqlServer -ErrorAction Stop

Write-Host "Acquiring an Azure AD access token for https://database.windows.net..."
$accessToken = az account get-access-token --resource https://database.windows.net --query accessToken -o tsv
if ([string]::IsNullOrWhiteSpace($accessToken)) {
    throw "Failed to acquire an access token for https://database.windows.net - is 'az login' (azure/login) already done, and does the signed-in principal have database access?"
}

# Convert the managed identity's client (application) ID to the binary SID Azure SQL expects for an
# external (Entra) principal. For an application/managed-identity principal the SID is the appId GUID's
# raw bytes (System.Guid.ToByteArray() order), hex-encoded - the same conversion Microsoft documents
# for creating contained users without the Directory Readers role.
try {
    $identityGuid = [System.Guid]::Parse($ManagedIdentityClientId)
}
catch {
    throw "ManagedIdentityClientId '$ManagedIdentityClientId' is not a valid GUID."
}
$sid = '0x' + (($identityGuid.ToByteArray() | ForEach-Object { $_.ToString('X2') }) -join '')

# Escape the identity name for the two SQL quoting contexts it appears in, so the generated T-SQL is
# robust even if the naming convention ever changes: doubled single quotes for the N'...' string
# literals, and doubled closing brackets for the [...] quoted identifiers. (The name is currently a
# deterministic Terraform local with none of these characters, but escaping keeps it injection-proof.)
$nameLiteral = $ManagedIdentityName.Replace("'", "''")
$nameIdent = $ManagedIdentityName.Replace("]", "]]")

# The workload service principal is the SQL server's Entra admin (azuread_administrator block in
# terraform/sql.tf), so this connection is authorized to create users and apply schema changes.
# Creating the user by SID (WITH SID = ..., TYPE = E) rather than FROM EXTERNAL PROVIDER means the SQL
# server identity never needs the Entra "Directory Readers" role.
$createUserSql = @"
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'$nameLiteral')
BEGIN
    CREATE USER [$nameIdent] WITH SID = $sid, TYPE = E;
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.database_role_members rm
    JOIN sys.database_principals r ON rm.role_principal_id = r.principal_id
    JOIN sys.database_principals m ON rm.member_principal_id = m.principal_id
    WHERE r.name = N'db_datareader' AND m.name = N'$nameLiteral'
)
BEGIN
    ALTER ROLE db_datareader ADD MEMBER [$nameIdent];
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.database_role_members rm
    JOIN sys.database_principals r ON rm.role_principal_id = r.principal_id
    JOIN sys.database_principals m ON rm.member_principal_id = m.principal_id
    WHERE r.name = N'db_datawriter' AND m.name = N'$nameLiteral'
)
BEGIN
    ALTER ROLE db_datawriter ADD MEMBER [$nameIdent];
END;
"@

Write-Host "Ensuring contained database user '$ManagedIdentityName' exists (by SID) with db_datareader/db_datawriter only..."
Invoke-SqlWithResumeRetry {
    Invoke-Sqlcmd -ServerInstance $SqlServerFqdn -Database $SqlDatabaseName -AccessToken $accessToken -Query $createUserSql -ConnectionTimeout 60 -ErrorAction Stop
}

if ($MigrationsScriptPath) {
    if (-not (Test-Path $MigrationsScriptPath)) {
        throw "Migrations script not found at '$MigrationsScriptPath'."
    }

    Write-Host "Applying EF Core migrations from '$MigrationsScriptPath' as the workload identity (SQL AAD admin)..."
    Invoke-SqlWithResumeRetry {
        Invoke-Sqlcmd -ServerInstance $SqlServerFqdn -Database $SqlDatabaseName -AccessToken $accessToken -InputFile $MigrationsScriptPath -ConnectionTimeout 60 -QueryTimeout 300 -ErrorAction Stop
    }
}
else {
    Write-Host "No -MigrationsScriptPath supplied - skipping migration apply."
}

Write-Host "SQL data-access configuration complete."
